# fly.toml app configuration file generated for habitask-api on 2024-01-22T14:28:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "habitask-api"
primary_region = "iad"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
 APP_NAME="Habitask"
 APP_ENV="production"
 APP_KEY="base64:F7h8JVZFbc1ziuam65riGuAEJs1aFWoKvVwmxY2utko="

 LOG_CHANNEL="stack"
 LOG_LEVEL="debug"

 DB_CONNECTION="mysql"
 DB_HOST="roundhouse.proxy.rlwy.net"
 DB_PORT="25928"
 DB_DATABASE="railway"
 DB_USERNAME="root"
 DB_PASSWORD="6daAEFhHB4affaF23CEGDHBF2aC5B4ee"

 BROADCAST_DRIVER="log"
 FILESYSTEM_DISK="local"
 QUEUE_CONNECTION="sync"
 SESSION_DRIVER="file"
 SESSION_LIFETIME="120"

 MAIL_MAILER="smtp"
 MAIL_HOST="sandbox.smtp.mailtrap.io"
 MAIL_PORT="2525"
 MAIL_USERNAME="23addc7c25be80"
 MAIL_PASSWORD="30bc7d739aca37"
 MAIL_FROM_ADDRESS="hello@example.com"
 MAIL_FROM_NAME="${APP_NAME}"


 PUSHER_PORT="443"
 PUSHER_SCHEME="https"
 PUSHER_APP_CLUSTER="mt1"

 VITE_APP_NAME="${APP_NAME}"
 VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
 VITE_PUSHER_HOST="${PUSHER_HOST}"
 VITE_PUSHER_PORT="${PUSHER_PORT}"
 VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
 VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

 SANCTUM_STATEFUL_DOMAINS="localhost,127.0.0.1"

 FACEBOOK_CLIENT_ID="882480830240079"
 FACEBOOK_CLIENT_SECRET="d17020560d7f60eb150a19adcd3a0402"
 FACEBOOK_REDIRECT_URI="https://habitaskweb-cuq87j7k.b4a.run/auth/callback"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
